[ci skip] repro fix

diff --git a/firmware/patches/0001-add-build-script.patch b/firmware/patches/0001-add-build-script.patch
--- a/firmware/patches/0001-add-build-script.patch
+++ b/firmware/patches/0001-add-build-script.patch
@@ -1,6 +1,6 @@
 diff --git a/build.sh b/build.sh
 new file mode 100755
-index 0000000..249268b
+index 0000000..2904d85
 --- /dev/null
 +++ b/build.sh
 @@ -0,0 +1,86 @@
@@ -58,34 +58,34 @@ index 0000000..249268b
 +#
 +build_uefi()
 +{
-+    # Normalise mtimes for reproducibility
-+    find . -type f -exec touch --date=@$SOURCE_DATE_EPOCH {} +
++	# Normalise mtimes for reproducibility
++	find . -type f -exec touch --date=@$SOURCE_DATE_EPOCH {} +
 +
 +	echo "      MAKE  BaseTools"
 +	make -C BaseTools
 +	source edksetup.sh
 +
 +	if [ "$ARCH_TARGET" = "x86" ]; then
-+	    echo "     BUILD  OvmfPkg"
++		echo "     BUILD  OvmfPkg"
 +
-+	    defines="${defines} -D SECURE_BOOT_ENABLE=TRUE -D TPM2_ENABLE=TRUE -D QEMU_PV_VARS=TRUE"
-+	    [ -n "$UEFI_DEBUG" ] && defines="${defines} -DDEBUG_ON_SERIAL_PORT"
++		defines="${defines} -D SECURE_BOOT_ENABLE=TRUE -D TPM2_ENABLE=TRUE -D QEMU_PV_VARS=TRUE"
++		[ -n "$UEFI_DEBUG" ] && defines="${defines} -DDEBUG_ON_SERIAL_PORT"
 +
-+	    build -a X64 -t $TOOLCHAIN -b $BUILD_TYPE --hash -p OvmfPkg/OvmfPkgX64.dsc ${defines}
-+	    cp Build/OvmfX64/${BUILD_TYPE}_${TOOLCHAIN}/FV/OVMF.fd firmware.fd
++		build -a X64 -t $TOOLCHAIN -b $BUILD_TYPE --hash -p OvmfPkg/OvmfPkgX64.dsc ${defines}
++		cp Build/OvmfX64/${BUILD_TYPE}_${TOOLCHAIN}/FV/OVMF.fd firmware.fd
 +
 +	elif [ "$ARCH_TARGET" = "arm64" ]; then
-+	    echo "     BUILD  ArmVirtQemuKernel"
++		echo "     BUILD  ArmVirtQemuKernel"
 +
-+	    defines="${defines} -D SECURE_BOOT_ENABLE=TRUE -D TPM2_ENABLE=TRUE -D QEMU_PV_VARS=TRUE"
-+	    [ -n "$UEFI_DEBUG" ] && defines="${defines} -DDEBUG_ON_SERIAL_PORT"
++		defines="${defines} -D SECURE_BOOT_ENABLE=TRUE -D TPM2_ENABLE=TRUE -D QEMU_PV_VARS=TRUE"
++		[ -n "$UEFI_DEBUG" ] && defines="${defines} -DDEBUG_ON_SERIAL_PORT"
 +
-+	    build -a AARCH64 -t $TOOLCHAIN -b $BUILD_TYPE --hash -p ArmVirtPkg/ArmVirtQemuKernel.dsc
-+	    cp Build/ArmVirtQemuKernel-AARCH64/${BUILD_TYPE}_${TOOLCHAIN}/FV/QEMU_EFI.fd firmware.fd
++		build -a AARCH64 -t $TOOLCHAIN -b $BUILD_TYPE --hash -p ArmVirtPkg/ArmVirtQemuKernel.dsc
++		cp Build/ArmVirtQemuKernel-AARCH64/${BUILD_TYPE}_${TOOLCHAIN}/FV/QEMU_EFI.fd firmware.fd
 +
 +	else
-+	    echo "ERROR: Unknown UEFI build target ${ARCH_TARGET}"
-+	    exit 1
++		echo "ERROR: Unknown UEFI build target ${ARCH_TARGET}"
++		exit 1
 +	fi
 +}
 +
